name: money_management
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  build_runner: ^2.3.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_expanded_tile: ^0.3.6
  flutter_slidable: ^2.0.0
  flutter_tab_indicator_styler: ^2.0.0
  flutter_toggle_tab: ^1.2.0
  google_nav_bar: ^5.0.6
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  intl: ^0.17.0
  hive: ^2.2.3
  month_year_picker: ^0.2.0+3
  vertical_percent_indicator: ^0.0.1
  flutter_svg: ^1.0.3
  awesome_snackbar_content: ^0.1.0
  shared_preferences: ^2.0.15
  google_fonts:
  font_awesome_flutter:
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: "assets/image/logo.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  assets:
    - assets/image/money-removebg-preview.png
    - assets/image/plan.jpg
    - assets/image/incom.jpg
    - assets/image/expenss.jpg
    - assets/image/bag - Copy.jpg
    - assets/image/food.jpg
    - assets/image/list.jpg
    - assets/image/monlogo.jpg
    - assets/image/travel .jpg
    - assets/image/logout.jpg
    - assets/image/plan-removebg-preview.png
    - assets/image/category.webp
    - assets/image/icon.png
    - assets/image/medical_edited.jpg
    - assets/image/shopping_edited.jpg
